server:
  port: 9527
spring:
  application:
    name: cloud-gateway-9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 从注册中心动态的创建路由，利用微服务名进行路由
      routes:
        - id: payment_routh1
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/eureka/**

        - id: payment_routh2
            uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

eureka:
  instance: # 自己在注册中心显示的名字
    instance-id: gateway9527
    prefer-ip-address: true # 在注册中心，鼠标移动到实例名字上时显示对应的ip
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka